/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>;

export interface Ancestry {
	boosts: string;
	custom: Generated<number>;
	description: string;
	enable: Generated<number>;
	flaws: string;
	hands: number;
	hp: number;
	id: string | null;
	img: string | null;
	languages: string;
	name: string;
	size: string;
	speed: number;
	traits: string;
	vision: string;
}

export interface Feat {
	action_type: string;
	custom: Generated<number>;
	description: string;
	enable: Generated<number>;
	id: string | null;
	name: string;
	rarity: string;
	traits: string;
	type: string;
}

export interface DB {
	ancestries: Ancestry;
	feats: Feat;
}
