/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>;

export interface CatalogEffect {
	created_at: Generated<string>;
	data: string;
	entry_id: string;
	id: string;
	type: string;
	updated_at: Generated<string>;
}

export interface CatalogEntry {
	created_at: Generated<string>;
	data: string;
	description: string | null;
	enabled: Generated<number>;
	id: string;
	level: number | null;
	name: string;
	rarity: string | null;
	slug: string;
	source_id: string;
	traits: string;
	type: string;
	updated_at: Generated<string>;
}

export interface CatalogPrerequisite {
	created_at: Generated<string>;
	entry_id: string;
	expression: string;
	id: string;
	updated_at: Generated<string>;
}

export interface CatalogRelation {
	created_at: Generated<string>;
	data: string | null;
	id: string;
	source_entry_id: string;
	target_entry_id: string;
	type: string;
	updated_at: Generated<string>;
}

export interface CatalogSource {
	approved: Generated<number>;
	created_at: Generated<string>;
	id: string;
	license: string | null;
	name: string;
	slug: string;
	type: string;
	updated_at: Generated<string>;
}

export interface DB {
	catalog_effect: CatalogEffect;
	catalog_entry: CatalogEntry;
	catalog_prerequisite: CatalogPrerequisite;
	catalog_relation: CatalogRelation;
	catalog_source: CatalogSource;
}
